### ISSUE TITLE
Как играть?

### ISSUE THREAD

**Issue by Mazdaywik** [bmstu-iu9/ptp2021-8-tabletop-game#52]
Открыл игру на двух отдельных окнах браузера. В обоих окнах вот такая картина:

![image](https://user-images.githubusercontent.com/1309859/134389253-e51f3e46-29a3-4949-a260-674790c25e44.png)

В консоли такая картинка:

![image](https://user-images.githubusercontent.com/1309859/134389283-436d5ea0-6a85-4a2e-a2dc-5bc88ba6a45c.png)

Браузер Edge Chromium, версия 93.0.961.52.

**Comment by Mazdaywik** [comment]
Забыл добавить: тыкаю на любой шестиугольник — выскакивает сообщение об ошибке:

![image](https://user-images.githubusercontent.com/1309859/134389495-95112cfd-2606-4937-9f9b-5f67a3b761e5.png)

**Comment by ivanfotbin** [comment]
Реализована техника игры hot seat - игра запускается с одного окна браузера. Синий игрок может выбирать только шестиугольники, соседствующие с шестиугольниками его цвета. Аналогично с красным

**Comment by ivanfotbin** [comment]
Игроки ходят по очереди. Можно отыграть соседний шестиугольник оппонента.

**Comment by Mazdaywik** [comment]
Собирал старой версией npm. Версию обновил — всё заработало.
